#!/usr/lib/ckan/default/bin/python

###############################################################
#
# Create tag vocabularies for Eawag Research Data Platform
# HvW - 2015-10-27
#
###############################################################

import os
import sys
import re
import argparse
from pprint import PrettyPrinter
import ckanapi

pp = PrettyPrinter(indent = 2)

host = "http://localhost:5000"
apikey = os.environ['CKAN_LOCAL_APIKEY_HVW_ADM']
#host = "http://eaw-ckan-dev1.eawag.wroot.emp-eaw.ch"
#apikey = os.environ['CKAN_DEV1_APIKEY_HVW_ADM']
ckan = ckanapi.RemoteCKAN(host, apikey=apikey)

# not used, currently
def sanitize_name(name):
    name_san = re.sub('[^0-9a-zA-Z]+', '-', name).lower()
    return(name_san)

def new_vocab(vocab_name, tag_file):
    ## check whether we already have that vocabulary name
    try:
        vocab = ckan.call_action('vocabulary_show', {'id': vocab_name})
        print("Vocabulary {} exists:".format(vocab_name))
        pp.pprint(vocab)
        return(2)
    except ckanapi.NotFound:
        with open(tag_file) as f:
            tagnames = [x.strip('\n') for x in f.readlines()]
        #tag_names = [sanitize_name(x) for x in tag_disp_names]
        vocab = ckan.call_action('vocabulary_create', {'name': vocab_name})
        for t in tagnames:
            ckan.call_action('tag_create', {'name': t, 'vocabulary_id': vocab['id']})
        vocab = ckan.call_action('vocabulary_show', {'id': vocab['id']})
        print("Created vocabulary {}:".format(vocab['name']))
        pp.pprint(vocab)

def del_vocabs(vocabname="*"):
    vocabs = ckan.call_action('vocabulary_list')
    if vocabname == "*":
        vocabids = [x['id'] for x in vocabs]
    else:
        vocabids = [x['id'] for x in vocabs if x["name"] == vocabname]
    print("vocabids: {}".format(vocabids))
    for id in vocabids:
        # delte all tags
        vocab = ckan.call_action('vocabulary_show', {'id': id})
        print("Deleting vocabulary {}".format(vocab["name"]))
        for tid, name in [(x['id'], x['name']) for x in vocab['tags']]:
            print("tid: {}".format(tid))
            print("tag-name: {}".format(name))
            ckan.call_action('tag_delete', {'id': tid, 'vocabulary_id': id})
        # delete vocabulary
        ckan.call_action('vocabulary_delete', {'id': id})

def show_vocabs():
    vocablist = ckan.call_action('vocabulary_list')
    pp.pprint(vocablist)
    # for voc in vocablist:
    #     ckan.call_api('vocabulary_show', voc['id'])

def update_vocab(add_tag):
    newtag = ckan.call_action('tag_create', {'name': add_tag[0],
                                             'vocabulary_id': add_tag[1]})
    print("Created new tag:")
    pp.pprint(newtag)

def delete_tag(del_tag):
    ckan.call_action('tag_delete', {'id': del_tag[0],
                                    'vocabulary_id': del_tag[1]})

def cli_parse():
    parser = argparse.ArgumentParser(description='Create tag-vocabulary')
    parser.add_argument('--clean', help='remove all tag-vocabularies first',
                        action='store_true')
    parser.add_argument('--del', metavar="vocab_name",
                        help="remove vocab_name", action='store')
    parser.add_argument('vocnam', metavar='vocabulary_name', nargs='?')
    parser.add_argument('vocdef', metavar='vocabuary_definition', nargs='?',
                        help='file containing a tag name in each line')
    parser.add_argument('--show', help='only show vocabularies',
                        action='store_true')
    parser.add_argument('--add-tag', help='new tag name', nargs=2,
                        metavar=('TAGNAME', 'VOCAB_ID'))
    parser.add_argument('--del-tag', help='delete tag', nargs=2,
                        metavar=('TAGNAME', 'VOCAB_ID'))
    
    args = vars(parser.parse_args())
    if (not (args['show'] or args['del'] or args['add_tag'] or args['del_tag'])) and (not (args['vocnam'] and args['vocdef'])):
        print("Too few arguments")
        parser.print_help()
        sys.exit(0)
    return(args['vocnam'], args['vocdef'], args['clean'], args['show'], args['del'], args['add_tag'], args['del_tag'])

    
if __name__ == '__main__':
    vocabname, vocabdeffile, clean, show, dele, add_tag, del_tag = cli_parse()
    if show:
        show_vocabs()
        ran = True
    if dele:
        del_vocabs(dele)
        ran = True
    if clean:
        del_vocabs()
        ran = True
    if add_tag:
        update_vocab(add_tag)
        ran = True
    if del_tag:
        delete_tag(del_tag)
        ran = True
    if vocabname and vocabdeffile:
        new_vocab(vocabname, vocabdeffile)
        print("Updated vocabularies:")
        show_vocabs()
    elif not ran:
        print("Too few arguments")
        sys.exit(2)

