#!/bin/bash

source "/usr/lib/ckan/default/bin/activate"

# We assume appropriate usernames are used in the form "username@host" in the *_HOST parameters if applicable.
# We assume there is passwordless ssh-login set up for all involved accounts.

TMPDIR="/tmp"

# Host to fetch from
SOURCE_HOST="eaw-test-ckan.eawag.wroot.emp-eaw.ch"
SOURCE_USER="ckan"
# Source absolute path to Filestore
SOURCE_DIR="/var/lib/ckan/default"

# Target host
TARGET_HOST="localhost"
#TARGET_USER="$USER"
# Target absolute path to Filestore
TARGET_DIR="/var/lib/ckan/"

# Target database
TARGET_DB="ckan_default"
TARGET_DB_USER="ckan_default"
# Source database
SOURCE_DB="ckan_default"
SOURCE_DB_USER="ckan_default"

# construct SOURCE and TARGEt for rsync
if [ -z "$SOURCE_HOST" ] || [ "$SOURCE_HOST" = "localhost" ]; then
    SOURCE="$SOURCE_DIR"
else
    SOURCE="${SOURCE_USER}@${SOURCE_HOST}:${SOURCE_DIR}"
fi

if [ -z "$TARGET_HOST" ] || [ "$TARGET_HOST" = "localhost" ]; then
    TARGET="$TARGET_DIR"
else
    TARGET="${TARGET_USER}@${TARGET_HOST}:${TARGET_DIR}"
fi

fetch_filestore() {
    echo "fetching Filestore:"
    echo
    cmd="rsync -rlptv ${SOURCE} ${TARGET}"
    echo $cmd
    eval $cmd
    echo
}

db_dump_remote() {
    echo "dumping database $SOURCE_DB on $SOURCE_HOST:"
    echo
    pg_dump -v -h "$SOURCE_HOST" -U "$SOURCE_DB_USER" "$SOURCE_DB" > "${TMPDIR}/ckan_dump.tmp"
    echo
}

db_reset_local() {
    dropdb -h "$TARGET_HOST" -U "$TARGET_DB_USER" "$TARGET_DB"
    createdb -h "$TARGET_HOST" -U postgres -O "$TARGET_DB_USER" "$TARGET_DB" -E utf-8
    sudo -u postgres psql -d $TARGET_DB -f /usr/share/postgresql/9.4/contrib/postgis-2.1/uninstall_postgis.sql
    sudo -u postgres psql -d $TARGET_DB -f /usr/share/postgresql/9.4/contrib/postgis-2.1/postgis.sql
    sudo -u postgres psql -d $TARGET_DB -f /usr/share/postgresql/9.4/contrib/postgis-2.1/spatial_ref_sys.sql
    sudo -u postgres psql -d $TARGET_DB -c "ALTER VIEW geometry_columns OWNER TO $TARGET_DB_USER;"
    sudo -u postgres psql -d $TARGET_DB -c "ALTER TABLE spatial_ref_sys OWNER TO $TARGET_DB_USER;"
    sudo -u postgres psql -d $TARGET_DB -c "SELECT postgis_full_version()"
    
}

db_clean_local() {
    echo "cleaning local CKAN database:"
    echo
    source /usr/lib/ckan/default/bin/activate
    paster --plugin=ckan db clean -c /etc/ckan/default/development.ini
    deactivate
    echo
}

db_load() {
    echo "loading ${TMPDIR}/ckan_dump.tmp into local CKAN database:"
    echo
    source /usr/lib/ckan/default/bin/activate
    paster --plugin=ckan db load -c /etc/ckan/default/development.ini  "${TMPDIR}/ckan_dump.tmp"
    rm "${TMPDIR}/ckan_dump.tmp"
    deactivate
    echo
}

ckan_sync() {
    db_dump_remote
    db_reset_local
    db_clean_local
    db_load
    fetch_filestore
}

ckan_sync
